FROM golang:1.26.4-alpine

WORKDIR /app

# Install Air untuk hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Jalankan Air secara otomatis saat container start
CMD ["air"]